"project_id": "865798"
"base_path": "."
"base_url": "https://api.crowdin.com"


"preserve_hierarchy": true

files: [
  {
    "source": "/lib/l10n/app_en.arb",
    "translation": "/lib/l10n/app_%two_letters_code%.arb",
  }
]