name: project_raco
description: "Project Raco App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  process_run: ^0.12.0
  flutter_lints: ^4.0.0
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/